name: NPM publish

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: v2.0.0

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version for release trigger
        uses: allenevans/set-env@v2.0.1
        if: ${{ github.event_name == 'release' }}
        with:
          PACKAGE_VERSION: ${{github.event.release.tag_name}}
      - name: Set version for workflow dispatch
        uses: allenevans/set-env@v2.0.1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          PACKAGE_VERSION: ${{ github.event.inputs.version }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm version ${{env.PACKAGE_VERSION}}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
