name: NPM publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: v2.0.0

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version for workflow dispatch
        uses: allenevans/set-env@v2.0.1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          PACKAGE_VERSION: ${{ github.event.inputs.version }}

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install

      - name: Setup GIT user
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Bump version for workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: npm version ${{env.PACKAGE_VERSION}} --allow-same-version

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
